import type { Category, Product, SiteSettings, Training } from "@/types/database";

export const demoSettings: SiteSettings = {
  id: "demo",
  site_name: "Merveill design",
  logo_url: null,
  favicon_url: null,
  hero_title: "Sacs artisanaux & box cadeaux sur mesure",
  hero_subtitle:
    "Élégance, savoir-faire et personnalisation — du premier regard à la livraison, à Ouagadougou et partout au Burkina Faso.",
  hero_image_url: null,
  whatsapp_number: "22600000000",
  contact_email: "mervelle-design@gmail.com",
  social_links: { instagram: "#", facebook: "#" },
  theme_config: {},
  seo_title: "Merveill design | Sacs & box Burkina Faso",
  seo_description:
    "Sacs à main artisanaux, coffrets cadeaux et formations. Commande sur mesure.",
  seo_keywords: "sac à main Ouagadougou, box cadeau Burkina Faso, formation maroquinerie",
  updated_at: new Date().toISOString(),
};

export const demoCategories: Category[] = [
  {
    id: "c1",
    name: "Sacs à main",
    slug: "sacs",
    type: "bag",
    sort_order: 1,
    created_at: "",
  },
  {
    id: "c2",
    name: "Box cadeaux",
    slug: "box-cadeaux",
    type: "box",
    sort_order: 2,
    created_at: "",
  },
  {
    id: "c3",
    name: "Formations",
    slug: "formations",
    type: "training",
    sort_order: 3,
    created_at: "",
  },
];

export const demoProducts: Product[] = [
  {
    id: "p1",
    name: "Sac cabas cuir nude",
    slug: "sac-cabas-cuir-nude",
    category_id: "c1",
    type: "bag",
    short_description: "Cabas structuré, finitions main, cuir pleine fleur.",
    description: null,
    base_price: 125000,
    pricing_mode: "starting_from",
    is_customizable: true,
    is_model_only: false,
    is_featured: true,
    is_published: true,
    cover_image_url:
      "https://images.unsplash.com/photo-1584917865442-de89df76afd3?w=800&q=80",
    tags: ["cabas", "cuir"],
    display_order: 1,
    stock: null,
    created_at: "",
    updated_at: "",
  },
  {
    id: "p2",
    name: "Mini sac bandoulière",
    slug: "mini-sac-bandouliere",
    category_id: "c1",
    type: "bag",
    short_description: "Format journée, lignes épurées.",
    description: null,
    base_price: 85000,
    pricing_mode: "starting_from",
    is_customizable: true,
    is_model_only: true,
    is_featured: false,
    is_published: true,
    cover_image_url:
      "https://images.unsplash.com/photo-1590874103328-eac38a683ce7?w=800&q=80",
    tags: ["bandoulière"],
    display_order: 2,
    stock: null,
    created_at: "",
    updated_at: "",
  },
  {
    id: "p3",
    name: "Coffret cadeau premium",
    slug: "coffret-cadeau-premium",
    category_id: "c2",
    type: "box",
    short_description: "Emballage sur mesure pour marques et événements.",
    description: null,
    base_price: null,
    pricing_mode: "quote",
    is_customizable: true,
    is_model_only: false,
    is_featured: true,
    is_published: true,
    cover_image_url:
      "https://images.unsplash.com/photo-1549465220-576843087d93?w=800&q=80",
    tags: ["coffret"],
    display_order: 1,
    stock: null,
    created_at: "",
    updated_at: "",
  },
];

export const demoTrainings: Training[] = [
  {
    id: "t1",
    title: "Initiation sac à main",
    slug: "initiation-sac",
    short_description: "Premiers pas : patronage, coupe, assemblage.",
    description: "Atelier présentiel — petit groupe.",
    price: 75000,
    pricing_mode: "fixed",
    duration: "2 jours",
    level: "débutant",
    mode: "presentiel",
    is_published: true,
    cover_image_url:
      "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80",
    display_order: 1,
    created_at: "",
    updated_at: "",
  },
  {
    id: "t2",
    title: "Perfectionnement box & packaging",
    slug: "perfectionnement-box",
    short_description: "Finitions, gabarits et personnalisation marque.",
    description: null,
    price: null,
    pricing_mode: "quote",
    duration: "3 jours",
    level: "intermédiaire",
    mode: "presentiel",
    is_published: true,
    cover_image_url:
      "https://images.unsplash.com/photo-1513475382583-d06e58bcb0e0?w=800&q=80",
    display_order: 2,
    created_at: "",
    updated_at: "",
  },
];
